window.CAT_ASSETS = [
  "HKa_cXOaMAA0WzZ.png",
  "HKa9phCaMAATekm.png",
  "HKaZr4GaQAAwabU.png",
  "HKb1XuyakAE63PT.png",
  "HKb2-VLbgAA41C9.png",
  "HKb9UgpbsAAzf_V.png",
  "HKbCTeSbgAA2A9T.png",
  "HKbdWCybIAA3D2v.png",
  "HKbh6V7bUAABLmc.png",
  "HKbHXoEbkAApMWK.png",
  "HKbJY-faMAA0oA7.png",
  "HKcBuVQaYAAY1Tf.png",
  "HKci7q9boAADfzE (1).png",
  "HKcIWRlaUAAihz4.png",
  "HKcJvDqaoAADpUd.png",
  "HKNyUUpaUAAQgSp.png",
  "HKQ0y7dbsAAzRNF.png",
  "HKQYkOtboAAh9Cf.png",
  "HKV_qItakAAVMrV.png",
  "HKW1W4caIAE2Z-P (1).png",
  "HKX0o90bMAAbCyv.png",
  "HKX2c-zboAANNBv.png",
  "HKX2XgKaEAAq8dS.png",
  "HKXHGxIaQAE0Cnl.png",
  "HKXInJyb0AAHzTd.png",
  "HKXjHH3bkAAyxay.png",
  "HKXSgaabcAAe4z_.png",
  "HKXw3JGaIAAgf7T.png",
  "HKYBu12bcAAfKUc.png",
  "HKYG-wSa0AATPON.png",
  "HKYMbuPaoAAleyz.png",
  "HKYOxKZbMAEOqNL.png",
  "HKYvA-IboAAcj3g.png",
  "HKZ7LztbsAAOGzr.png",
  "HKZ-R8zacAA5ulg.png",
];
